### ISSUE TITLE
Message is lacking some padding-top

### ISSUE THREAD

**Issue by kensanata** [bburns/emacswiki-light-theme#14]
Here's a tiny issue about padding, I guess?

http://i.imgur.com/MCU8hdq.png

(Firefox 46.0.1 on a Mac)

**Comment by bburns** [comment]
Okay, here's the fix, with a couple of minor dark theme fixes also - 

https://raw.githubusercontent.com/bburns/emacswiki-light-theme/master/light.css

**Comment by kensanata** [comment]
Installed the latest CSS on Emacs Wiki. Thanks!
