### ISSUE TITLE
Portrait Support

### ISSUE THREAD

**Issue by kensanata** [bburns/emacswiki-light-theme#2]
When I look at the News page, I see a feature that's sometimes used on the wiki: Portrait support. That's when you use `[new::]` which will expand into `[new:AlexSchroeder:2015-01-03 22:52 UTC]` which will inline an image from your homepage. Here's some [CSS documentation](https://oddmuse.org/wiki/Portraits_Support_Extension#h5o-1) on the topic. Some floating of the div, a smaller font for the name, a max-size for the image, perhaps?

**Comment by bburns** [comment]
This is partially working at the moment - I need to get the image and caption working together better as one element. 

And that's good to know about the [new::] - I was wondering how everyone put in the time like that! Maybe we could add something about it to the bottom of the edit page? It's in the link to the formatting rules page but I don't think I ever made it through the whole thing - I might add a line about it to the HowTo page. 

Cheers, 
Brian
