### ISSUE TITLE
Underlining of links and line height

### ISSUE THREAD

**Issue by kensanata** [bburns/emacswiki-light-theme#3]
When looking at this screenshot, it seems that either line height should be bigger or the underlining of links should be closer to the baseline?
http://imgur.com/vfn8X2d

**Comment by kensanata** [comment]
Perhaps a simple `line-height: 1.5em;` for the body element would be enough.

**Comment by bburns** [comment]
Okay, I'll try that also - right now it's using a dotted bottom border, which is a trick for getting a dotted underline, but it's not perfect - Firefox has a new dotted underline style, but it's not in Chrome yet. So increasing the line height might be best.

**Comment by bburns** [comment]
I tried the new dotted underline style - it works in Firefox, though in Chrome it just renders as a gray underline, which looks okay. I think this will do for now, though we could still try increasing the line height - I'll try that out for a while also and see how it looks.
